


const SIGN_UP_SUCCESSFULLY=1009;
const LOGIN_SUCCESSFULLY=1010;
const FOLLOWING=1011;
const DELETE=1012;
const SOMETHING_WENT_WRONG=1013;


export {SIGN_UP_SUCCESSFULLY,LOGIN_SUCCESSFULLY,FOLLOWING,DELETE,SOMETHING_WENT_WRONG} ;
