const SIGN_UP_SUCCESSFULLY=1015;
const LOGIN_SUCCESSFULLY=1016;
const FOLLOWING=1017;
const DELETE=1018;
const SOMETHING_WENT_WRONG=1019;
const PLAYLIST_NOT_EXIST=1008;


export {SIGN_UP_SUCCESSFULLY,LOGIN_SUCCESSFULLY,FOLLOWING,DELETE,SOMETHING_WENT_WRONG,PLAYLIST_NOT_EXIST} ;
