


const SIGN_UP_SUCCESSFULLY=1013;
const LOGIN_SUCCESSFULLY=1014;
const FOLLOWING=1015;
const DELETE=1016;
const SOMETHING_WENT_WRONG=1017;


export {SIGN_UP_SUCCESSFULLY,LOGIN_SUCCESSFULLY,FOLLOWING,DELETE,SOMETHING_WENT_WRONG} ;
